config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ## AUTHENTICATION
  devise_for :users,  path: 'profile', controllers: { registrations: "registrations" }

  ## HOMEPAGE
  authenticated do
    root to: 'user_opportunities#index', :defaults => { :status => :review }
  end
  root to: 'pages#home'

  ## STATIC PAGES
  get '/styleguide', to: 'pages#styleguide'
  get '/extension', to: 'pages#extension'

  ## USER PROFILE
  get '/profile', to: 'profiles#index'
  get '/map', to: 'profiles#map'

  ## OPPORTUNITIES
  # Build the following routes
  # GET ['review', 'pending', 'applied', 'trash']
  statuses = UserOpportunity.statuses.keys.map(&:to_sym)
  # status = [:review, :pending, :applied, :trash]
  statuses.each do |status|
    # then we create the routes
    # passing a parameter :status to the function in user_opportunity_controller :
    match "/opportunities/#{status.to_s}" =>
      'user_opportunities#index',
      :defaults => { :status => status }, via: :get
  end

  resources :user_opportunities,
    path: 'opportunities',
    only: [:index, :show, :update, :destroy]

  ## EVENTS
  resources :events,
    only: [:index, :create, :update, :destroy]

  ## CRITERIA & IMPORTANCES
  resources :importances,
    only: [:index, :edit, :update] do
      resources :criteria,
        except: [:index, :show]
    end
  put '/importances/', to: 'importances#update_importances', as: :update_importances

  ## API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: [ :create ]
      resources :opportunities, only: [:create]
    end
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  def index
    @importances = policy_scope(Importance)
    @importances_values = @importances.all.map { |i| [i.name, i.value] }.to_h
  end

  def map
    @markers_pending = @user_opportunities.where(status: :pending).map do |u_op|
      title = "#{u_op.title} @#{u_op.company_name}"
      {
        title: title,
        lat: u_op.opportunity.latitude,
        lng: u_op.opportunity.longitude,
        infoWindow: {
          content: "<p>#{title}</p>"
        }
      }
    end

    @markers_applied = @user_opportunities.where(status: :applied).map do |u_op|
      title = "#{u_op.title} @#{u_op.company_name}"
      {
        title: title,
        lat: u_op.opportunity.latitude,
        lng: u_op.opportunity.longitude,
        infoWindow: {
          content: "<p>#{title}</p>"
        }
      }
    end

    authorize @user_opportunities
  end
end

app/views/profiles/index.html.erb
<div id="criterium" class="center-content-wrapper">
  <div class="container">
    <div class="row">
      <div class="col">
        <h2>My Profile</h2>
      </div>
    </div>
    <div class= "row mb-0">
      <div class="p-1 col-lg-6 mb-2">
        <div class="p-3 light-box">
          <h4>Criteria</h4>
          <div class="d-flex flex-column justify-content-between">
            <div class="section-content mb-4">
              <%= component 'radar', importances_values: @importances_values %>
            </div>
            <div class="profile-edit-criteria mb-3">
              <div class="d-flex justify-content-around">
                <%= link_to 'Modify Criteria', edit_importance_path(id: Importance.names.keys.first.to_sym), class: 'btn btn-primary' %>
                <%= link_to 'Modify Importances', importances_path, class: 'btn btn-primary' %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="p-1 col-lg-3 col-md-6 mb-2">
        <div class="p-3 light-box">
          <div class="profile-applications-status">
            <h4>Status</h4>
            <div class="d-flex flex-column">
              <div class="pl-1 pr-1 profile-not-reviewed d-flex justify-content-between">
                <%= link_to 'Not reviewed', opportunities_review_path, class: 'text-dark'%>
                <p><%= @user_opportunities.where(status: :review).count %></p>
              </div>
              <div class="pl-1 pr-1  profile-pending d-flex justify-content-between">
                <%= link_to 'Pending', opportunities_pending_path, class: 'text-dark'%>
                <p><%= @user_opportunities.where(status: :pending).count %></p>
              </div>
              <div class="pl-1 pr-1  profile-applied d-flex justify-content-between">
                <%= link_to 'Applied', opportunities_applied_path, class: 'text-dark'%>
                <p><%= @user_opportunities.where(status: :applied).count %></p>
              </div>
              <div class="pl-1 pr-1  profile-deadlines d-flex justify-content-between text-danger">
                <%= link_to 'Calendar', events_path, class: 'text-danger'%>
                <% if current_user.events.size.nil? %>
                  <p>0</p>
                <% else %>
                  <p><%= current_user.events.size  %></p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="p-1 col-lg-3 col-md-6 mb-2">
        <div class="p-3 light-box">
          <div class="profile-settings">
            <h4>Settings</h4>
            <div class="d-flex flex-column align-items-center">
              <div>
                <div class="settings-icon mt-1 mb-3">
                  <i class="fas fa-cog fa-7x" style="color: #adb5bd"></i>
                </div>
                <div class="button-settings mb-3">
                <%= link_to 'Settings', edit_user_registration_path, class: 'btn btn-primary' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/map.html.erb
<section class="row">
  <div class="p-1 col-lg-12">
    <div>
      <div class="p-3 border border-primary bg-white">
        <h4>Your Opportunity Map</h4>
        <div class="map-legend d-flex m-2">
          <div class="map-legend-applied m-2">
            <i class="fas fa-map-marker-alt fa-2x" style="color: #0b409c"></i>
            <span class="align-bottom">Pending</span>
          </div>
          <div class="map-legend-pending m-2">
            <i class="fas fa-map-marker-alt fa-2x" style="color: #dd0a35"></i>
            <span class="align-bottom">Applied</span>
          </div>
        </div>
        </div>
      <div id="map" class="rounded" style="width: 100%; height: 50%;" data-pending="<%= @markers_pending.to_json %>" data-applied="<%= @markers_applied.to_json %>"></div>
    </div>
  </div>
</section>