config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ## AUTHENTICATION
  devise_for :users,  path: 'profile', controllers: { registrations: "registrations" }

  ## HOMEPAGE
  authenticated do
    root to: 'user_opportunities#index', :defaults => { :status => :review }
  end
  root to: 'pages#home'

  ## STATIC PAGES
  get '/styleguide', to: 'pages#styleguide'
  get '/extension', to: 'pages#extension'

  ## USER PROFILE
  get '/profile', to: 'profiles#index'
  get '/map', to: 'profiles#map'

  ## OPPORTUNITIES
  # Build the following routes
  # GET ['review', 'pending', 'applied', 'trash']
  statuses = UserOpportunity.statuses.keys.map(&:to_sym)
  # status = [:review, :pending, :applied, :trash]
  statuses.each do |status|
    # then we create the routes
    # passing a parameter :status to the function in user_opportunity_controller :
    match "/opportunities/#{status.to_s}" =>
      'user_opportunities#index',
      :defaults => { :status => status }, via: :get
  end

  resources :user_opportunities,
    path: 'opportunities',
    only: [:index, :show, :update, :destroy]

  ## EVENTS
  resources :events,
    only: [:index, :create, :update, :destroy]

  ## CRITERIA & IMPORTANCES
  resources :importances,
    only: [:index, :edit, :update] do
      resources :criteria,
        except: [:index, :show]
    end
  put '/importances/', to: 'importances#update_importances', as: :update_importances

  ## API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: [ :create ]
      resources :opportunities, only: [:create]
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_js_global_object.html.erb
<script>const SuricatGlobalObject = {};</script>

app/views/shared/_left_menu.html.erb
<div class="left-menu">
  <%= link_to opportunities_review_path, class: "left-menu-item-link" do %>
    <div class="left-menu-item">
      <div class="left-menu-item-icon">
        <span class="badge badge-primary">new</span>
      </div>
      <div class="left-menu-item-text">
          Offers to review
          <span id="opportunity-number-review" class="opportunity-number light">(67)</span>
      </div>
    </div>
  <% end %>
  <%= link_to opportunities_pending_path, class: "left-menu-item-link" do %>
    <div class="left-menu-item">
      <div class="left-menu-item-icon text-danger">
        <i class="fas fa-flag"></i>
      </div>
      <div class="left-menu-item-text">
          Pending
          <span id="opportunity-number-pending" class="opportunity-number light">(55)</span>
      </div>
    </div>
  <% end %>
  <%= link_to opportunities_applied_path, class: "left-menu-item-link" do %>
    <div class="left-menu-item">
      <div class="left-menu-item-icon text-success">
        <i class="fa fa-check-circle"></i>
      </div>
      <div class="left-menu-item-text">
          Applied
          <span id="opportunity-number-apply" class="opportunity-number light">(2)</span>
      </div>
    </div>
  <% end %>
  <%= link_to opportunities_trash_path, class: "left-menu-item-link" do %>
    <div class="left-menu-item">
      <div class="left-menu-item-icon text-gray">
        <i class="fas fa-trash"></i>
      </div>
      <div class="left-menu-item-text">
          Trash
      </div>
    </div>
  <% end %>
  <%= link_to events_path, class: "left-menu-item-link" do %>
    <div class="left-menu-item">
      <div class="left-menu-item-icon">
        <i class="far fa-calendar-alt"></i>
      </div>
      <div class="left-menu-item-text">
          Calendar
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_meta.html.erb
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">
<meta property="og:title" content="<%= meta_title %>" />
<!-- Facebook Open Graph data -->
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= asset_pack_path 'media/images/banner-suricat-og.jpg' %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />
<!-- Facebook Open Graph data -->
<link href="<%= asset_pack_path 'media/images/favicon.ico' %>" rel="shortcut icon" type="image/x-icon" />

app/views/shared/_navbar.html.erb
<div class="nav-container">
  <nav id="navbar-suricat" class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
    <%= link_to root_path, class: "navbar-suricat-brand" do %>
      <%= image_tag asset_pack_path('media/images/logo.svg') %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarToggler">
      <% if user_signed_in? %>
        <ul class="navbar-nav">
          <!-- Links when logged in -->
            <li class="nav-item <%= 'active' if current_page?(root_path) %>" data-step="1" data-intro="<%= t('intro.home') %>">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item <%= 'active' if current_page?(user_opportunities_path) %>">
              <%= link_to "Recommandations", user_opportunities_path, class: "nav-link" %>
            </li>
        </ul>
      <% end %>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <!-- Links when logged in -->
          <li class="nav-item <%= 'active' if current_page?(profile_path) %>">
            <%= link_to "#{current_user.first_name} #{current_user.last_name}", profile_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>

        <% else %>
          <!-- Login link (when logged out) -->
          <li class="nav-item">
            <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/shared/_opportunity_info.html.erb
<div class='job-offer-user-infos light-box section-content'>
  <table>
    <tr>
      <th scope="row">
        Status
      </td>
      <td>
        <%= t("opportunity.status.#{opportunity.status}") %>
      </td>
    </tr>
    <tr>
      <th scope="row">
        Deadline
      </td>
      <td>
        <%= opportunity.deadline %>
      </td>
    </tr>
    <tr>
      <th scope="row">
        Start date
      </td>
      <td>
        <%= opportunity.start_date %>
      </td>
    </tr>
    <tr>
      <th scope="row">
        Contract
      </td>
      <td>
        <% unless opportunity.contract_type.nil? %>
          <%= t("opportunity.contract_type.#{opportunity.contract_type}") %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th scope="row">
        Structure
      </td>
      <td>
        <% unless opportunity.company_structure.nil? %>
          <%= t("company.structure.#{opportunity.company_structure}") %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th scope="row">
        Industry
      </td>
      <td>
        <%= opportunity.sector_name %>
      </td>
    </tr>
    <tr>
      <th scope="row">
        Salary
      </td>
      <td>
        <%= opportunity.salary.nil? ? 'N/A' : "#{opportunity.salary}  €" %>
      </td>
    </tr>
  </table>
</div>