config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ## AUTHENTICATION
  devise_for :users,  path: 'profile', controllers: { registrations: "registrations" }

  ## HOMEPAGE
  authenticated do
    root to: 'user_opportunities#index', :defaults => { :status => :review }
  end
  root to: 'pages#home'

  ## STATIC PAGES
  get '/styleguide', to: 'pages#styleguide'
  get '/extension', to: 'pages#extension'

  ## USER PROFILE
  get '/profile', to: 'profiles#index'
  get '/map', to: 'profiles#map'

  ## OPPORTUNITIES
  # Build the following routes
  # GET ['review', 'pending', 'applied', 'trash']
  statuses = UserOpportunity.statuses.keys.map(&:to_sym)
  # status = [:review, :pending, :applied, :trash]
  statuses.each do |status|
    # then we create the routes
    # passing a parameter :status to the function in user_opportunity_controller :
    match "/opportunities/#{status.to_s}" =>
      'user_opportunities#index',
      :defaults => { :status => status }, via: :get
  end

  resources :user_opportunities,
    path: 'opportunities',
    only: [:index, :show, :update, :destroy]

  ## EVENTS
  resources :events,
    only: [:index, :create, :update, :destroy]

  ## CRITERIA & IMPORTANCES
  resources :importances,
    only: [:index, :edit, :update] do
      resources :criteria,
        except: [:index, :show]
    end
  put '/importances/', to: 'importances#update_importances', as: :update_importances

  ## API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: [ :create ]
      resources :opportunities, only: [:create]
    end
  end
end

app/models/user_opportunity.rb
# frozen_string_literal: true

class UserOpportunity < ApplicationRecord
  enum status: [:review, :pending, :applied, :trash]
  belongs_to :user
  belongs_to :opportunity
  has_one :job, through: :opportunity
  has_one :company, through: :opportunity
  has_one :sector, through: :opportunity
  after_initialize :init

  validates :user, presence: true
  validates :opportunity, presence: true
  validates :personnal_grade, presence: true

  before_save :grade_calculation

  (Opportunity.attribute_names - attribute_names).each do |attr|
    delegate attr.to_sym, to: :opportunity, allow_nil: true
  end

  [Job, Company, Sector].each do |obj|
    (obj.attribute_names - attribute_names).each do |attr|
      object_name = obj.name.underscore
      delegate attr.to_sym, to: object_name, allow_nil: true, prefix: true
    end
  end

  def init
    self.status ||= :review
    self.personnal_grade ||= 0
  end

  def self.find_or_create(user:, opportunity:, params: nil)
    item = find_by(user: user, opportunity: opportunity)
    return item unless item.nil?

    raise ArgumentError, 'Missing params' if params.nil?

    UserOpportunity.create(
      user: user,
      opportunity: opportunity,
      personnal_grade: params[:stars]
    )
  end

  # ! start methods for automatic_grade calculation !
  def grade_calculation
    grade_calculator = GradeService.new(user, opportunity)
    self.automatic_grade = grade_calculator.call
  end
end

app/controllers/user_opportunities_controller.rb
# frozen_string_literal: true

class UserOpportunitiesController < ApplicationController
  layout 'sidebar'

  before_action :set_user_opportunity, only: [:show, :update, :destroy]

  def index
    if current_user.intro
      @intro = false
      @status = params[:status]
      @user_opportunities_displayed = @user_opportunities.where(status: @status) unless @status.nil?
      @user_opportunities_displayed = @user_opportunities_displayed.sort_by { |op| [op.personnal_grade || 0, op.automatic_grade || 0] }.reverse unless @user_opportunities_displayed.nil?
    else
      @intro = true
      current_user.intro = true
      current_user.save
      @user_opportunities_displayed = [UserOpportunity.first]
    end
  end

  def show
    authorize @user_opportunity
    @opportunity = UserOpportunity.find(params[:id])
    @marker = if @opportunity.nil?
                { lat: nil, lng: nil }
              else
                {
                  lat: @opportunity.latitude,
                  lng: @opportunity.longitude
                }
              end
  end

  def update
    @user_opportunity.status = params[:status]
    @user_opportunity.save
    authorize @user_opportunity
    redirect_to opportunities_review_path if params[:from] == 'show'
  end

  def destroy
    @user_opportunity.destroy
    authorize @user_opportunity
  end

  private

  def set_user_opportunity
    @user_opportunity = UserOpportunity.find(params[:id])
  end

  def user_opportunity_params
    params.require(:user_opportunity).permit(:status, :opportunity_id)
  end
end

app/views/user_opportunities/destroy.js.erb
var d = document.querySelector("[data-job-id='<%= @user_opportunity.id %>']");
var animations = ["animationend", "animationend", "webkitAnimationEnd", "oanimationend", "MSAnimationEnd"];
animations.forEach((animation) => {
  d.addEventListener(animation, () => {
    d.remove();
  }, false );
});
d.className += (' removed-item');

<% [:review, :pending, :applied].each do |status| %>
  document.querySelector('#opportunity-number-<%= status %>').innerText = '(<%=  @user_opportunities.where(status: status).count %>)';
<% end %>

app/views/user_opportunities/index.html.erb
<% unless @status.nil? %>
  <% if @status == :review %>
    <h2><span class="badge badge-primary">new</span> Offers to <%= @status %></h2>
  <% elsif @status == :pending %>
    <h2><i class="fas fa-flag text-danger"></i> <%= @status.capitalize %> offers</h2>
    <% elsif @status == :applied %>
    <h2><i class="fa fa-check-circle text-success"></i> <%= @status.capitalize %> offers</h2>
  <% else %>
    <h2><i class="fas fa-trash text-gray"></i> <%= @status.capitalize %></h2>
  <% end %>
<% end %>

<% unless @user_opportunities_displayed.nil? %>
  <div id="job-cards" data-step="3" data-intro="<%= t('intro.joblist') %>">
    <div class="controls">
      <!-- class="search" automagically makes an input a search field. -->
      <input class="search form-control" placeholder="Search" />
      <!-- class="sort" automagically makes an element a sort buttons. The date-sort value decides what to sort by. -->
      <button class="sort btn btn-secondary" data-sort="jobcard-auto-grade">
        Sort by grade
      </button>
    </div>

    <ul class="list list-unstyled">
    <% @user_opportunities_displayed.each do |user_opportunity| %>
      <li>
        <%= component 'job_card', opportunity: user_opportunity %>
      </li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @intro %>
  <script>
    SuricatGlobalObject.intro = true;
  </script>
<% end %>

app/views/user_opportunities/show.html.erb
<div id="job-container" class="row">
  <div class="col">
    <div class="job-offer">
      <div class="row">

        <div class="col-lg-12">
          <div class="row">

            <div class="col">
              <div class="job-offer-top">
                <% if @user_opportunity.logo.nil? %>
                  <%= image_tag asset_pack_path("media/images/company.png"), class: 'img-center' %>
                <% else %>
                  <%= image_tag @user_opportunity.logo, class: 'img-center' %>
                <% end %>
                <div class="job-offer-top--description">
                  <h3><%= sanitize @user_opportunity.title %></h3>
                  <h4><%= sanitize @user_opportunity.company_name %></h4>
                </div>

              </div>
            </div>

            <div class="col right-side text-right">
              <div class="trash-show zoom">
                <h4>
                  <%= link_to user_opportunity_path(@opportunity, status: :trash) + "&from=show", method: :patch, remote: false do %>
                    <i class="fas fa-trash text-gray"></i>
                  <% end %>
                </h4>
              </div>
              <div class="job-offer-top--companylink">
                <%= link_to 'Apply', @user_opportunity.url, target: "_blank", class: 'btn btn-primary' %>
              </div>

              <div class="job-offer-top--grades">
                <strong><%= @user_opportunity.personnal_grade %>/5</strong>
                <strong><%= @user_opportunity.automatic_grade %>%</strong>

              </div>
            </div>

          </div>
        </div>



        <div class="col-sm-12 d-md-none">
          <%= render partial: 'shared/opportunity_info', locals: { opportunity: @user_opportunity } %>
        </div>

        <div class="col-sm-12">
          <div class="job-offer-job--description">
            <h4>Job description</h4>
            <p class="text-justify">
              <% unless @user_opportunity.job_description.nil? %>
                <%= Kramdown::Document.new(@user_opportunity.job_description).to_html.html_safe %>
              <% end %>
            </p>
          </div>
        </div>

      </div>
    </div>
  </div>
  <div class="job-info d-none d-md-block">
    <%= render partial: 'shared/opportunity_info', locals: { opportunity: @user_opportunity } %>
    <div class="mt-2" id="map" style="width: 100%; height: 40%" data-marker="<%= @marker.to_json %>"></div>
  </div>
</div>

app/views/user_opportunities/update.js.erb
var d = document.querySelector("[data-job-id='<%= @user_opportunity.id %>']");
var animations = ["animationend", "animationend", "webkitAnimationEnd", "oanimationend", "MSAnimationEnd"];
animations.forEach((animation) => {
  d.addEventListener(animation, () => {
    d.remove();
  }, false );
});
d.className += (' removed-item');

<% [:review, :pending, :applied].each do |status| %>
  document.querySelector('#opportunity-number-<%= status %>').innerText = '(<%=  @user_opportunities.where(status: status).count %>)';
<% end %>