config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ## AUTHENTICATION
  devise_for :users,  path: 'profile', controllers: { registrations: "registrations" }

  ## HOMEPAGE
  authenticated do
    root to: 'user_opportunities#index', :defaults => { :status => :review }
  end
  root to: 'pages#home'

  ## STATIC PAGES
  get '/styleguide', to: 'pages#styleguide'
  get '/extension', to: 'pages#extension'

  ## USER PROFILE
  get '/profile', to: 'profiles#index'
  get '/map', to: 'profiles#map'

  ## OPPORTUNITIES
  # Build the following routes
  # GET ['review', 'pending', 'applied', 'trash']
  statuses = UserOpportunity.statuses.keys.map(&:to_sym)
  # status = [:review, :pending, :applied, :trash]
  statuses.each do |status|
    # then we create the routes
    # passing a parameter :status to the function in user_opportunity_controller :
    match "/opportunities/#{status.to_s}" =>
      'user_opportunities#index',
      :defaults => { :status => status }, via: :get
  end

  resources :user_opportunities,
    path: 'opportunities',
    only: [:index, :show, :update, :destroy]

  ## EVENTS
  resources :events,
    only: [:index, :create, :update, :destroy]

  ## CRITERIA & IMPORTANCES
  resources :importances,
    only: [:index, :edit, :update] do
      resources :criteria,
        except: [:index, :show]
    end
  put '/importances/', to: 'importances#update_importances', as: :update_importances

  ## API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: [ :create ]
      resources :opportunities, only: [:create]
    end
  end
end

app/models/importance.rb
# frozen_string_literal: true

class Importance < ApplicationRecord
  default_scope { order(:name) }
  enum name: [:contract_type, :company_structure, :sector_name, :job_name, :location, :salary]
  belongs_to :user
  has_many :criteria, dependent: :destroy
end

app/controllers/importances_controller.rb
# frozen_string_literal: true

class ImportancesController < ApplicationController
  before_action :set_importance, only: [:edit, :update]

  def index
    @importances_values = current_user.importances_value
  end

  def update_importances
    importance_values_params.each do |name, value|
      importance = Importance.find_by(name: name, user: current_user)
      importance.value = value
      importance.save
      @user_opportunities.each(&:save)
      authorize importance
    end

    # proposes to download the extension if the user is new (intro==true)
    if current_user.intro
      redirect_to profile_path
    else
      redirect_to extension_path
    end
  end

  def edit
    @current_values = current_criteria_values
  end

  def update
    values = criterium_values_params

    # delete previous values
    @importance.criteria.destroy_all

    # rewrite them all
    values.each_with_index do |value, index|
      criterium = Criterium.new(value: value, rank: index)
      criterium.importance = @importance
      criterium.save
    end

    if @importance.save
      @user_opportunities.each(&:save)
      redirect_next
    else
      render :edit
    end
  end

  private

  def set_importance
    @importance = Importance.find_by(user: current_user, name: params[:id].to_sym)
    authorize @importance
  end

  def importance_values_params
    params.require(:importance).permit!
  end

  def criterium_values_params
    params.require(:importance).permit(values: [])['values'].reject { |x| x.nil? || x == '' }
  end

  def redirect_next
    index = Importance.names.keys.find_index(params[:id].to_s)
    if !index.nil? && index + 1 < Importance.names.count
      next_importance = Importance.names.keys.at(index + 1).to_sym
      redirect_to edit_importance_path(id: next_importance)
    else
      # reset params
      params = []
      redirect_to importances_path
    end
  end

  def current_criteria_values
    @importance.criteria.map(&:value)
  end
end

app/views/importances/edit.html.erb
<div id="criterium" class="center-content-wrapper">
  <div class="container-fluid">
    <div class="flex-sign">
      <h1>Your Criteria</h1>
      <h2>Let us know more about you to build your profil</h2>


      <div id="mydiv" class="card-question section-content">

        <h3><%= t("importance.name.#{@importance.name}") %></h3>
        <%= simple_form_for @importance, url: importance_path(id: @importance.name) do |f| %>

          <div class="form-group">
            <label for="importance_value">Select your criteria of search <strong>ordered</strong> by preference</label>
            <% case @importance.name.to_sym %>
            <% when :contract_type %>
              <select class="form-control select optional"
                title="Pick one or more items"
                multiple="multiple"
                name="importance[values][]"
                id="importance__value">
                <% Opportunity.contract_types.each do |type, value| %>
                  <option value="<%= value %>" <%= 'selected="selected"' if @current_values.include?(value.to_s) %>>
                    <%= t("opportunity.contract_type.#{type}") %>
                  </option>
                <% end %>
              </select>

            <% when :company_structure %>
              <select class="form-control select optional"
                title="Pick one or more items"
                multiple="multiple"
                name="importance[values][]"
                id="importance__value">
                <% Company.structures.each do |type, value| %>
                  <option value="<%= value %>" <%= 'selected="selected"' if @current_values.include?(value.to_s) %>>
                    <%= t("company.structure.#{type}") %>
                  </option>
                <% end %>
              </select>

            <% when :sector_name %>
              <select class="form-control select optional"
                title="Pick one or more items"
                multiple="multiple"
                name="importance[values][]"
                id="importance__value">
                <% SectorCategory.all.each do |category| %>
                  <optgroup label="<%= sanitize category.name %>">
                    <% category.sectors.each do |sector| %>
                      <option value="<%= sector.id %>" <%= 'selected="selected"' if @current_values.include?(sector.id.to_s) %>>
                        <%= sanitize sector.name %>
                      </option>
                    <% end %>
                  </optgroup>
                <% end %>
              </select>

            <% when :job_name %>
              <select class="form-control select optional"
                title="Pick one or more items"
                multiple="multiple"
                name="importance[values][]"
                id="importance__value">
                <% JobCategory.all.each do |category| %>
                  <optgroup label="<%= sanitize category.name %>">
                    <% category.jobs.each do |job| %>
                      <option value="<%= job.id %>" <%= 'selected="selected"' if @current_values.include?(job.id.to_s) %>>
                        <%= sanitize job.name %>
                      </option>
                    <% end %>
                  </optgroup>
                <% end %>
              </select>

            <% when :location %>
              <br>
              <script>SuricatGlobalObject.tags = (<%= @current_values.to_json.html_safe %>).map(JSON.parse);</script>
              <input type="text" class="form-control" id="importance__value" data-location="true">

            <% when :salary %>
              <input type="text" class="form-control" name="importance[values][]" id="importance__value" value=<%= @current_values.first %>>

            <% end %>
            <input type="hidden" name="importance[values][]">
          </div>

          <%= f.button :submit, "Save criteria", class: "btn-primary" %>
        <% end %>
      </div>

      <div class="section-content">
        <ul class="list-unstyled multi-steps">
          <% Importance.names.each do |name, value| %>
            <% if name == @importance.name %>
              <li class="is-active"><%= link_to t("importance.name.#{name}"), edit_importance_path(id: name) %></li>
            <% else %>
              <li><%= link_to t("importance.name.#{name}"), edit_importance_path(id: name) %></li>
            <% end %>
          <% end %>
        </ul>
      </div>

    </div>
  </div>
</div>

app/views/importances/index.html.erb
<div id="importance" class="center-content-wrapper">
  <div class="container">
    <%= form_tag update_importances_path, method: :put do %>
      <section class="row mb-3">
        <div class="col-sm-12">
          <div class="d-flex justify-content-between">
            <div class="importance-headers">
              <h2>Your Preferences</h2>
              <h4>Set your importance criteria</h4>
            </div>
            <div class="importance-submit d-flex align-items-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </div>
      </section>
      <section class="row">
        <div class="col-sm-4 border-right border-primary">
          <div class="importance-criteria d-flex flex-column justify-content-between">
            <% @importances_values.each do |name, value| %>
              <div class="criteria-bar d-flex flex-column justify-content-between">
                <h6><%= t("importance.name.#{name}") %></h6>
                <div class="form-group">
                  <input type="range" min="0" max="100" name="importance[<%= name %>]"value="<%= value %>" class="form-control-range" id="formControlRange" data-importance="<%= t("importance.name.#{name}") %>">
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col-sm-8 d-flex flex-column justify-content-center">
          <div class="section-content">
            <%= component 'radar', importances_values: @importances_values %>
          </div>
        </div>
      </section>
    <% end %>
  </div>
</div>